/******************
 Problem #: 2

 Author: Jared Morrison

 Prompt:
    "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
     the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of
     the even-valued terms."

 Start Date: 04/15/2024 01:00 am
 Completion: 04/15/2024 01:30 am
 Answer: 4613732
 ******************/

#include <iostream>
#define MAX 4000000

using namespace std;

void printFibToN(int n);

int main(){
    printFibToN(MAX);
    return 0;
}

void printFibToN(int n){
    unsigned int nextTerm = 0;
    unsigned int currTerm = 1;
    unsigned int prevTerm = 0;
    unsigned int sum = 0;

    do{
        nextTerm = currTerm + prevTerm;
        prevTerm = currTerm;
        currTerm = nextTerm;
        if (nextTerm % 2 == 0){
            sum += nextTerm;
        }
        cout << nextTerm << endl;
    }while(currTerm + prevTerm <= n);

    cout << "\n\n\nSUM: " << sum << endl;

}